services:
  mariadb:
    restart: always
    container_name: mariadb
    init: true
    build: requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - .env
    volumes:
      - mariadb-test:/var/lib/mysql
    networks:
      - docker-network
  
  wordpress:
    restart: always
    container_name: wordpress
    init: true
    build: requirements/wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - WORDPRESS_EMAIL=${WORDPRESS_EMAIL}
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp-test:/var/www/html
    networks:
      - docker-network

  nginx:
    restart: always
    container_name: nginx
    init: true
    build: requirements/nginx
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-test:/var/www/html
    networks:
      - docker-network

volumes:
  mariadb-test:
    driver_opts:
      type: none
      device: /home/vinguyen/data/mariadb
      o: bind
  wp-test:
    driver_opts:
      type: none
      device: /home/vinguyen/data/wordpress
      o: bind  

networks:
  docker-network:
    name: docker-network
    driver: bridge