version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html:ro
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - inception

networks:
  inception:
    driver: bridge
