services:
  mariadb:
    container_name: mariadb-test
    build: requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mariadb-test:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - test-network

volumes:
  mariadb-test:

networks:
  docker-network:
    name: docker-network
    driver: bridge