services:
  mariadb:
    container_name: mariadb-test
    build: requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb-test:/var/lib/mysql
    networks:
      - docker-network
  
  wordpress:
    container_name: wordpress-test
    build: requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp_test:/var/www/html
    networks:
      - docker-network

  nginx:
    container_name: nginx-test
    build: requirements/nginx
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp-test:/var/www/html
    networks:
      - docker-network

volumes:
  mariadb-test:
  wp-test:

networks:
  docker-network:
    name: docker-network
    driver: bridge